### PR TITLE
My personal upgrade for fvtt11 for anyone interested

### PR DESCRIPTION
**Pull request by p4535992**

### CODE REVIEW

**Comment by theripper93** [comment]
What is not working in v11 that requires an update?

**Comment by p4535992** [comment]
just update the db and make searchable on the module list

**Comment by theripper93** [comment]
Ye it's just item\tables\journals compendiums, i imagine it doesn't need that much updating

**Comment by p4535992** [comment]
people always ask me where to download this stuff... and they always get scared when they see yellow....

**Pull request merged**
